name: tremtec-infra
description: Cloudflare infrastructure for TremTec

runtime:
  name: nodejs
  options:
    packagemanager: bun

backend:
  url: $PULUMI_BACKEND_URL

config:
  pulumi:tags:
    value:
      pulumi:template: typescript
