config:
  tremtec-infra:zoneId: 41af03736c37c38d8d6b2db7c02548a4
  tremtec-infra:accountId: b2386820ea46b6a9a2eff9e3f8ff5182
  tremtec-infra:environment: dev
  tremtec-infra:github-id:
    secure: v1:Dn1PXr+Y+emrX1En:gn3Flz5liWl9HFI7CZE/ty/V4mVx98KMglNTTT7ZngG+DsOb
  tremtec-infra:github-secret:
    secure: v1:0Bul+Efqp9XwxtlI:gpmwcFAtZc3Qwc2YU/+WGre6WaGWhlPZegdO5xmtZ+G83W5Y+8AkbgSRq0TkMpLKHH5ug1ag+Pw=
  tremtec-infra:google-id:
    secure: v1:GqN7YUIeOQA9Me8J:HFxJVR1UIQOUep76R1X1m3X2pOB8Sg==
  tremtec-infra:google-secret:
    secure: v1:knpktllXcpol7Dwd:5dksa8plPbwW6VJfvYu4I6+5XUyu8A==
encryptionsalt: v1:eKPeaC58kZU=:v1:IRZCCGjmUqefFw7y:NZHFuj7AGvoz4YK0OdywnmIg3i9srg==
